static const char* opcodenames[256] = {
    "LD r,s",
    "LD d,r",
    "LD d,n",
    "LD A,(ss)",
    "LD (dd),A",
    "LD A,(C)",
    "LD (C),A",
    "LDD A,(HL)",
    "LDD (HL),A",
    "LDI A,(HL)",
    "LDI (HL),A",
    "LDH (n),A",
    "LDH A,(N)",
    "LDD dd,nn",
    "LD (nn),SP",
    "LD SP,HL",
    "LD HL,(SP+e)",
    "PUSH ss",
    "POP dd",
    "ADD A,s",
    "ADC A,s",
    "SUB s",
    "SBC A,s",
    "AND s",
    "OR s",
    "XOR s",
    "CP s",
    "INC s",
    "DEC s",
    "ADD HL,ss",
    "ADD SP,e",
    "INC ss",
    "DEC ss",
    "SWAP s",
    "DAA",
    "CPL",
    "CCF",
    "SCF",
    "NOP",
    "HALT",
    "STOP",
    "DI",
    "EI",
    "RLCA",
    "RLA",
    "RRCA",
    "RRA",
    "RLC s",
    "RL s",
    "RRC s",
    "RR s",
    "SLA s",
    "SRA s",
    "SRL s",
    "BIT b,s",
    "SET b,s",
    "RES b,s",
    "JP nn",
    "JP cc,nn",
    "JP (HL)",
    "JR e",
    "JR cc,e",
    "CALL nn",
    "CALL cc,nn",
    "RST f",
    "RET",
    "RET cc",
    "RETI"
}
